language: go

go:
  - tip

notifications:
  webhooks:
    urls:
      - http://weixin.chenlixin.net/update
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: never
    on_start: [always|never|change] # default: never